### ISSUE TITLE
Train classifiers on the cleaned data sets

### ISSUE THREAD

**Issue by poclecoqq** [KhaledBadran/FairBoost#2]
## Description
In our study, we will need to compare FairBoost to baselines. The baselines are each individually trained model. 
Depends on #1. 

## Tasks
- [ ] Train a Linear regression / Logistic regression model on each data set
- [ ] Train a Random Forrest on each data set
- [ ] Train a NN on each data set?

## Tasks on the paper
- [ ] TODO
